### ISSUE TITLE
Doctrine cache

### ISSUE THREAD

**Issue by luxifer** [florianv/FlorianvSwapBundle#4]
Any plan on adding other doctrine cache possibilities, or maybe allow to specify a service id instead of a cache name ta match a class.

My point is, I want to use `predis` https://github.com/doctrine/cache/blob/master/lib/Doctrine/Common/Cache/PredisCache.php with your lib, but it's not just a class to instantiate, this class needs a reference to a `Predis\Client` instance.

**Comment by florianv** [comment]
I don't really have time to implement it but yes we could also accept a service id under the doctrine configuration section.

**Comment by florianv** [comment]
Fixed in version `2.1.0`
