### ISSUE TITLE
UnsupportedCurrencyPairException exception is thrown.

### ISSUE THREAD

**Issue by zeitnot** [florianv/FlorianvSwapBundle#8]
Sometimes UnsupportedCurrencyPairException is thrown. I do not know in which case this problem occurs but I have an idea. As I see the default http adapter is file_get_contents. The target page may have http redirections. If so, that adapter can not handle redirections.

**Comment by florianv** [comment]
You can use a custom http adapter https://github.com/florianv/FlorianvSwapBundle/blob/master/Resources/doc/index.md#custom-http-adapter

**Comment by zeitnot** [comment]
@florianv thanks, it works.

**Comment by florianv** [comment]
@zeitnot Np :)
